fix(release): update workflow

diff --git a/.github/workflows/release-package.yaml b/.github/workflows/release-package.yaml
--- a/.github/workflows/release-package.yaml
+++ b/.github/workflows/release-package.yaml
@@ -16,6 +16,14 @@ jobs:
       - run: npm test
       - run: npm run build
 
+      # Check that 'dist' folder exists after build
+      - name: Verify 'dist' folder exists
+        run: |
+          if [ ! -d "dist" ]; then
+            echo "'dist' folder not found!"
+            exit 1
+          fi
+
   publish-gpr:
     needs: build
     runs-on: ubuntu-latest
